[set_user]: Success!
[set_psswd]: Success!
[login]: Success!
[get_History]->HeadersInfo: Success!
[get_History]->Basis: Success!
[get_History]->InfosHistory: Success!
[get_History]->PDF: Success!
[set_user]: Success!
[set_psswd]: Success!
[login]: Failure! MaxRetryError: ("HTTPConnectionPool(host='127.0.0.1', port=43155): Max retries exceeded with url: /session/6094e160a9c452ab1e84fe53686d1190/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5dbffac88>: Failed to establish a new connection: [Errno 111] Connection refused'))",)
[get_History]->HeadersInfo: Failure! MaxRetryError: ("HTTPConnectionPool(host='127.0.0.1', port=43155): Max retries exceeded with url: /session/6094e160a9c452ab1e84fe53686d1190/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5db8b70f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",)!
[get_History]->Basis: Failure! MaxRetryError: ("HTTPConnectionPool(host='127.0.0.1', port=43155): Max retries exceeded with url: /session/6094e160a9c452ab1e84fe53686d1190/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5dbec7f60>: Failed to establish a new connection: [Errno 111] Connection refused'))",)!
[get_History]->InfosHistory: Failure! MaxRetryError: ("HTTPConnectionPool(host='127.0.0.1', port=43155): Max retries exceeded with url: /session/6094e160a9c452ab1e84fe53686d1190/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5db8b3940>: Failed to establish a new connection: [Errno 111] Connection refused'))",)!
[get_History]->PDF: Success!
